import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Colors } from '@/constants/theme';
import { cvTemplates, mockJobOptions } from '@/lib/mock-ai-tools';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, Share, StyleSheet, Text, TouchableOpacity, useColorScheme, View } from 'react-native';

export default function GenerateCVScreen() {
  const router = useRouter();
  const colorScheme = useColorScheme();
  const colors = Colors[colorScheme ?? 'light'];
  const [selectedTemplate, setSelectedTemplate] = useState(cvTemplates[0].id);
  const [selectedJob, setSelectedJob] = useState<string>("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [isGenerated, setIsGenerated] = useState(false);
  const [activeTab, setActiveTab] = useState<'customize' | 'preview'>('customize');
  const [showJobPicker, setShowJobPicker] = useState(false);

  const handleGenerate = async () => {
    setIsGenerating(true);
    // Simulate AI generation
    await new Promise(resolve => setTimeout(resolve, 3000));
    setIsGenerating(false);
    setIsGenerated(true);
    setActiveTab('preview');
  };

  const handleDownload = async () => {
    try {
      await Share.share({
        message: 'CV generated by Svype AI',
        title: 'My CV'
      });
    } catch (error) {
      Alert.alert('Error', 'Failed to share CV');
    }
  };

  const handleShare = async () => {
    try {
      await Share.share({
        message: 'Check out my CV generated with Svype!',
        title: 'My CV'
      });
    } catch (error) {
      Alert.alert('Error', 'Failed to share CV');
    }
  };

  const selectedJobData = mockJobOptions.find(j => j.id === selectedJob);

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      {/* Header */}
      <View style={[styles.header, { backgroundColor: colors.card, borderBottomColor: colors.border }]}>
        <View style={styles.headerContent}>
          <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
            <Ionicons name="chevron-back" size={24} color={colors.cardForeground} />
          </TouchableOpacity>
          <View style={styles.headerText}>
            <Text style={[styles.headerTitle, { color: colors.cardForeground }]}>
              Generate CV
            </Text>
            <Text style={[styles.headerSubtitle, { color: colors.mutedForeground }]}>
              Create AI-powered CVs tailored to jobs
            </Text>
          </View>
        </View>
      </View>

      {/* Tabs */}
      <View style={[styles.tabsContainer, { backgroundColor: colors.muted + '40' }]}>
        <TouchableOpacity
          style={[
            styles.tab,
            activeTab === 'customize' && { backgroundColor: colors.card }
          ]}
          onPress={() => setActiveTab('customize')}
        >
          <Ionicons 
            name="brush-outline" 
            size={16} 
            color={activeTab === 'customize' ? colors.cardForeground : colors.mutedForeground} 
          />
          <Text style={[
            styles.tabText,
            { color: activeTab === 'customize' ? colors.cardForeground : colors.mutedForeground }
          ]}>
            Customize
          </Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[
            styles.tab,
            activeTab === 'preview' && { backgroundColor: colors.card },
            !isGenerated && styles.tabDisabled
          ]}
          onPress={() => isGenerated && setActiveTab('preview')}
          disabled={!isGenerated}
        >
          <Ionicons 
            name="eye-outline" 
            size={16} 
            color={activeTab === 'preview' && isGenerated ? colors.cardForeground : colors.mutedForeground} 
          />
          <Text style={[
            styles.tabText,
            { color: activeTab === 'preview' && isGenerated ? colors.cardForeground : colors.mutedForeground }
          ]}>
            Preview
          </Text>
        </TouchableOpacity>
      </View>

      <ScrollView 
        style={styles.scrollView}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.content}>
          {activeTab === 'customize' && (
            <>
              {/* Template Selection */}
              <Card style={styles.card}>
                <CardContent>
                  <Text style={[styles.sectionTitle, { color: colors.cardForeground }]}>
                    Choose Template
                  </Text>
                  <View style={styles.templatesGrid}>
                    {cvTemplates.map((template) => (
                      <TouchableOpacity
                        key={template.id}
                        onPress={() => setSelectedTemplate(template.id)}
                        style={[
                          styles.templateCard,
                          {
                            borderColor: selectedTemplate === template.id ? colors.primary : colors.border,
                            backgroundColor: selectedTemplate === template.id ? colors.primary + '0D' : 'transparent'
                          }
                        ]}
                      >
                        <View style={[styles.templatePreview, { backgroundColor: colors.primary + '10' }]}>
                          <Ionicons name="document-text-outline" size={40} color={colors.primary + '40'} />
                        </View>
                        <View style={styles.templateInfo}>
                          <Text style={[styles.templateName, { color: colors.cardForeground }]}>
                            {template.name}
                          </Text>
                        </View>
                      </TouchableOpacity>
                    ))}
                  </View>
                </CardContent>
              </Card>

              {/* Job Selection */}
              <Card style={styles.card}>
                <CardContent>
                  <View style={styles.cardHeader}>
                    <View style={styles.cardHeaderText}>
                      <Text style={[styles.sectionTitle, { color: colors.cardForeground }]}>
                        Tailor for Job (Optional)
                      </Text>
                      <Text style={[styles.cardDescription, { color: colors.mutedForeground }]}>
                        Select a job to customize your CV with relevant keywords and skills
                      </Text>
                    </View>
                    <Badge variant="secondary" style={styles.aiBadge}>
                      <Ionicons name="sparkles" size={12} color={colors.mutedForeground} />
                      <Text style={[styles.aiBadgeText, { color: colors.mutedForeground }]}>
                        AI Powered
                      </Text>
                    </Badge>
                  </View>

                  <TouchableOpacity 
                    style={[styles.selectTrigger, { 
                      backgroundColor: colors.card,
                      borderColor: colors.border 
                    }]}
                    onPress={() => setShowJobPicker(!showJobPicker)}
                  >
                    <Text style={[
                      styles.selectText,
                      { color: selectedJob ? colors.cardForeground : colors.mutedForeground }
                    ]}>
                      {selectedJob 
                        ? selectedJob === "none" 
                          ? "General CV (no specific job)"
                          : `${selectedJobData?.title} - ${selectedJobData?.company}`
                        : "Select a job or leave blank for general CV"
                      }
                    </Text>
                    <Ionicons 
                      name={showJobPicker ? "chevron-up" : "chevron-down"} 
                      size={20} 
                      color={colors.mutedForeground} 
                    />
                  </TouchableOpacity>

                  {showJobPicker && (
                    <View style={[styles.jobPicker, { backgroundColor: colors.muted + '40', borderColor: colors.border }]}>
                      <TouchableOpacity
                        style={[styles.jobOption, selectedJob === "none" && { backgroundColor: colors.primary + '10' }]}
                        onPress={() => {
                          setSelectedJob("none");
                          setShowJobPicker(false);
                        }}
                      >
                        <Text style={[styles.jobTitle, { color: colors.cardForeground }]}>
                          General CV (no specific job)
                        </Text>
                      </TouchableOpacity>
                      {mockJobOptions.map((job) => (
                        <TouchableOpacity
                          key={job.id}
                          style={[styles.jobOption, selectedJob === job.id && { backgroundColor: colors.primary + '10' }]}
                          onPress={() => {
                            setSelectedJob(job.id);
                            setShowJobPicker(false);
                          }}
                        >
                          <Text style={[styles.jobTitle, { color: colors.cardForeground }]}>
                            {job.title}
                          </Text>
                          <Text style={[styles.jobCompany, { color: colors.mutedForeground }]}>
                            {job.company}
                          </Text>
                        </TouchableOpacity>
                      ))}
                    </View>
                  )}

                  {selectedJob && selectedJob !== "none" && (
                    <View style={[styles.aiOptimization, { 
                      backgroundColor: colors.primary + '0D',
                      borderColor: colors.primary + '33'
                    }]}>
                      <View style={styles.aiOptimizationContent}>
                        <Ionicons name="sparkles" size={20} color={colors.primary} />
                        <View style={styles.aiOptimizationText}>
                          <Text style={[styles.aiOptimizationTitle, { color: colors.cardForeground }]}>
                            AI Optimization Active
                          </Text>
                          <Text style={[styles.aiOptimizationDescription, { color: colors.mutedForeground }]}>
                            Your CV will be optimized with keywords from the job description, relevant experience highlighted, and skills matched to requirements.
                          </Text>
                        </View>
                      </View>
                    </View>
                  )}
                </CardContent>
              </Card>

              {/* Profile Preview */}
              <Card style={styles.card}>
                <CardContent>
                  <Text style={[styles.sectionTitle, { color: colors.cardForeground }]}>
                    Your Information
                  </Text>
                  <View style={[styles.profilePreview, { backgroundColor: colors.muted + '80' }]}>
                    <View style={[styles.profileAvatar, { backgroundColor: colors.primary + '1A' }]}>
                      <Text style={[styles.profileAvatarText, { color: colors.primary }]}>
                        JD
                      </Text>
                    </View>
                    <View style={styles.profileInfo}>
                      <Text style={[styles.profileName, { color: colors.cardForeground }]}>
                        John Doe
                      </Text>
                      <Text style={[styles.profileTitle, { color: colors.mutedForeground }]}>
                        Senior Full-Stack Developer
                      </Text>
                      <View style={styles.profileBadges}>
                        <Badge variant="outline" style={styles.profileBadge}>
                          <Text style={styles.profileBadgeText}>5+ years experience</Text>
                        </Badge>
                        <Badge variant="outline" style={styles.profileBadge}>
                          <Text style={styles.profileBadgeText}>10 skills</Text>
                        </Badge>
                        <Badge variant="outline" style={styles.profileBadge}>
                          <Text style={styles.profileBadgeText}>3 companies</Text>
                        </Badge>
                      </View>
                    </View>
                  </View>
                  <Text style={[styles.profileNote, { color: colors.mutedForeground }]}>
                    Data from your profile. You can edit in{' '}
                    <Text 
                      style={[styles.profileLink, { color: colors.primary }]}
                      onPress={() => router.push('/(jobseeker)/profile')}
                    >
                      Profile Settings
                    </Text>
                  </Text>
                </CardContent>
              </Card>

              {/* Generate Button */}
              <Button
                onPress={handleGenerate}
                disabled={isGenerating}
                style={styles.generateButton}
              >
                {isGenerating ? (
                  <>
                    <ActivityIndicator size="small" color="#fff" style={styles.buttonIcon} />
                    <Text style={styles.buttonText}>Generating with AI...</Text>
                  </>
                ) : (
                  <>
                    <Ionicons name="sparkles" size={16} color="#fff" style={styles.buttonIcon} />
                    <Text style={styles.buttonText}>Generate CV</Text>
                  </>
                )}
              </Button>
            </>
          )}

          {activeTab === 'preview' && (
            <>
              {/* CV Preview */}
              <Card style={styles.card}>
                <CardContent>
                  <View style={[styles.cvPreview, { backgroundColor: '#fff' }]}>
                    <View style={styles.cvContent}>
                      <View style={[styles.cvHeader, { borderBottomColor: colors.primary }]}>
                        <Text style={styles.cvName}>John Doe</Text>
                        <Text style={styles.cvJobTitle}>Senior Full-Stack Developer</Text>
                      </View>
                      <View style={styles.cvSections}>
                        <View style={styles.cvSection}>
                          <Text style={[styles.cvSectionTitle, { color: colors.primary }]}>
                            CONTACT
                          </Text>
                          <Text style={styles.cvText}>john.doe@example.com</Text>
                          <Text style={styles.cvText}>+44 7700 900123</Text>
                          <Text style={styles.cvText}>London, UK</Text>
                        </View>
                        <View style={styles.cvSection}>
                          <Text style={[styles.cvSectionTitle, { color: colors.primary }]}>
                            PROFESSIONAL SUMMARY
                          </Text>
                          <Text style={styles.cvTextGray}>
                            Experienced full-stack developer with 5+ years building scalable web applications...
                          </Text>
                        </View>
                        <View style={styles.cvSection}>
                          <Text style={[styles.cvSectionTitle, { color: colors.primary }]}>
                            EXPERIENCE
                          </Text>
                          <View style={styles.cvExperience}>
                            <Text style={styles.cvExperienceTitle}>Senior Developer - Tech Corp</Text>
                            <Text style={styles.cvExperienceDate}>2021 - Present</Text>
                          </View>
                        </View>
                      </View>
                    </View>
                  </View>
                </CardContent>
              </Card>

              {/* Actions */}
              <View style={styles.actionsGrid}>
                <Button
                  variant="outline"
                  onPress={handleShare}
                  style={styles.actionButton}
                >
                  <Ionicons name="share-outline" size={16} color={colors.primary} />
                  <Text style={[styles.actionButtonText, { color: colors.primary }]}>
                    Share
                  </Text>
                </Button>
                <Button
                  onPress={handleDownload}
                  style={styles.actionButton}
                >
                  <Ionicons name="download-outline" size={16} color="#fff" />
                  <Text style={styles.downloadButtonText}>Download PDF</Text>
                </Button>
              </View>
            </>
          )}
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: 40,
  },
  header: {
    marginTop: 40,
    paddingTop: 16,
    paddingBottom: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backButton: {
    padding: 4,
  },
  headerText: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  headerSubtitle: {
    fontSize: 13,
  },
  tabsContainer: {
    flexDirection: 'row',
    padding: 4,
    margin: 16,
    marginBottom: 0,
    borderRadius: 12,
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    borderRadius: 8,
  },
  tabDisabled: {
    opacity: 0.5,
  },
  tabText: {
    fontSize: 13,
    fontWeight: '600',
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: 16,
  },
  card: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 16,
  },
  templatesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  templateCard: {
    flex: 1,
    minWidth: '45%',
    borderWidth: 2,
    borderRadius: 12,
    overflow: 'hidden',
  },
  templatePreview: {
    aspectRatio: 3 / 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  templateInfo: {
    padding: 8,
  },
  templateName: {
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  cardHeaderText: {
    flex: 1,
    marginRight: 8,
  },
  cardDescription: {
    fontSize: 13,
    marginTop: 4,
  },
  aiBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  aiBadgeText: {
    fontSize: 11,
  },
  selectTrigger: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
  },
  selectText: {
    fontSize: 14,
    flex: 1,
  },
  jobPicker: {
    marginTop: 8,
    borderRadius: 12,
    borderWidth: 1,
    overflow: 'hidden',
  },
  jobOption: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.05)',
  },
  jobTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 2,
  },
  jobCompany: {
    fontSize: 12,
  },
  aiOptimization: {
    marginTop: 16,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
  },
  aiOptimizationContent: {
    flexDirection: 'row',
    gap: 12,
  },
  aiOptimizationText: {
    flex: 1,
  },
  aiOptimizationTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 4,
  },
  aiOptimizationDescription: {
    fontSize: 12,
    lineHeight: 18,
  },
  profilePreview: {
    flexDirection: 'row',
    gap: 12,
    padding: 12,
    borderRadius: 12,
    marginBottom: 12,
  },
  profileAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileAvatarText: {
    fontSize: 18,
    fontWeight: '700',
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 2,
  },
  profileTitle: {
    fontSize: 13,
    marginBottom: 8,
  },
  profileBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  profileBadge: {
    paddingVertical: 2,
    paddingHorizontal: 6,
  },
  profileBadgeText: {
    fontSize: 11,
  },
  profileNote: {
    fontSize: 11,
  },
  profileLink: {
    textDecorationLine: 'underline',
  },
  generateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    marginBottom: 16,
  },
  buttonIcon: {
    marginRight: 8,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  cvPreview: {
    borderRadius: 12,
    overflow: 'hidden',
  },
  cvContent: {
    padding: 24,
  },
  cvHeader: {
    borderBottomWidth: 2,
    paddingBottom: 12,
    marginBottom: 12,
  },
  cvName: {
    fontSize: 24,
    fontWeight: '700',
    color: '#000',
  },
  cvJobTitle: {
    fontSize: 16,
    color: '#666',
  },
  cvSections: {
    gap: 12,
  },
  cvSection: {
    gap: 4,
  },
  cvSectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 6,
  },
  cvText: {
    fontSize: 12,
    color: '#000',
  },
  cvTextGray: {
    fontSize: 12,
    color: '#555',
  },
  cvExperience: {
    gap: 2,
  },
  cvExperienceTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#000',
  },
  cvExperienceDate: {
    fontSize: 11,
    color: '#666',
  },
  actionsGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: '600',
  },
  downloadButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
});
